### ISSUE TITLE
Community Exchange Introduction & Tracking

### ISSUE THREAD

**Issue by radville** [Ammar-Raneez/SDGP-ONCO#54]
👋 Hi @Ammar-Raneez,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX.

You mentioned in your submission that you wanted to submit a `Learn` repo. This means that you would like to teach students, step by step, how to build this project. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you! :octocat: 

**CX Issues**:

- [x] https://github.com/Ammar-Raneez/SDGP-ONCO/issues/55
- [x] https://github.com/Ammar-Raneez/SDGP-ONCO/issues/56
- [x] https://github.com/Ammar-Raneez/SDGP-ONCO/issues/57
- [x] https://github.com/Ammar-Raneez/SDGP-ONCO/issues/58
- [x] https://github.com/Ammar-Raneez/SDGP-ONCO/issues/59

**Comment by Ammar-Raneez** [comment]
Sounds like a plan 😁

**Comment by radville** [comment]
Thanks for completing all the tasks! I'll leave this open until I can let you know when to submit to CX! ✨

**Comment by Ammar-Raneez** [comment]
Alrighty 😄
